#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

# panel
tint2 &

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 5
bspc config border_width 1

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#rules
bspc rule -a URxvt desktop='^1' 
bspc rule -a Pcmanfm desktop='^2'
bspc rule -a firefox desktop='^3' 
bspc rule -a Geany desktop='^4'
bspc rule -a Thonny desktop='^4'
bspc rule -a TelegramDesktop desktop= '^5'
bspc rule -a obsidian desktop= '^6'
bspc rule -a Simplenote desktop= '^6'
bspc rule -a Deadbeef desktop= '^7'
